### ISSUE TITLE
[Cast Docs] Codelab

### ISSUE THREAD

**Issue by JonasVautherin** [googlecast/CastVideos-chrome#40]
Running the `app-done` from [here](https://developers.google.com/cast/codelabs/cast-videos-chrome#2) doesn't work. My `http-server` fails with:

```
[Mon Nov 28 2022 00:37:41 GMT+0100 (Central European Standard Time)]  "GET /" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at module.exports.ResponseStream.(anonymous function) [as setHeader] (/usr/local/lib/node_modules/http-server/node_modules/union/lib/response-stream.js:100:34)
    at Object.exports.(anonymous function) (/usr/local/lib/node_modules/http-server/lib/core/status-handlers.js:57:7)
    at Readable.stream.on (/usr/local/lib/node_modules/http-server/lib/core/index.js:339:22)
    at Readable.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by JonasVautherin** [comment]
That was a problem due to my nodejs version being too old. Sorry for the noise :see_no_evil:
